repos:
  - repo: https://github.com/psf/black
    rev: 24.3.0
    hooks:
      - id: black

  - repo: local
    hooks:
      - id: run-pytest
        name: Run pytest
        entry: bash -c 'PYTHONPATH=$(pwd) pytest'
        language: system
        types: [python]
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ./gcloud-key.json
      GOOGLE_CLOUD_PROJECT: theravproject
