name: Deploy to EC2

on:
  push:
    branches: [main]  # or your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build and push Docker image
      run: |
        docker build -t ravprojectdev/rag:latest .
        echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        docker push ravprojectdev/rag:latest

    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull ravprojectdev/rag:latest
          docker stop my_container || true
          docker rm my_container || true
          echo "${{ secrets.GCLOUD_KEY_JSON_B64 }}" | base64 -d > /tmp/gcloud-key.json
          docker run -d \
            --name my_container \
            -v /tmp/gcloud-key.json:/rag/credentials/gcloud-key.json \
            -p 8000:8000 \
            ravprojectdev/rag:latest
