name: Flask Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      SBERT_API_URL: ${{ secrets.SBERT_API_URL }}
      MONGODB_URI: ${{ secrets.MONGODB_URI }}
      MONGODB_DB: ${{ secrets.MONGODB_DB }}
      MONGODB_VECTOR_COLLECTION: ${{ secrets.MONGODB_VECTOR_COLLECTION }}
      COLLECTION_INDEX: ${{ secrets.COLLECTION_INDEX }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_CLOUD_PROJECT_ID: ${{ secrets.GOOGLE_CLOUD_PROJECT_ID }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcloud-key.json

    steps:
      - uses: actions/checkout@v4

      - name: Write Google credentials file
        run: |
          echo "${{ secrets.GCLOUD_KEY_JSON_B64 }}" | base64 --decode > ${{ github.workspace }}/gcloud-key.json

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          PYTHONPATH=. pytest rag
